services:
  - type: web
    name: drowsiness-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
